name: InvitationLabel
on:
  issues:
    types:
      - labeled

jobs:
  build:
    if:  github.event.label.name == 'approved'
    name: Add collaborator!
    runs-on: ubuntu-latest
    steps:
      - uses: blackgirlbytes/invite-collaborator-action@main
        name: Perform invitation action
        env:
          # REQUIRED
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          APP_ID: ${{ secrets.APP_ID }}
          CLIENT_SECRET:  ${{ secrets.CLIENT_SECRET }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          INSTALLATION_ID:  ${{ secrets.INSTALLATION_ID }}
          # OPTIONAL
          ORG: false